id: 1e3ba083d9f8415388ee1ad8e8ecaec3
initial_creation_type: ebook
created_at: 20/05/2021
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །དགེ་ཚུལ་གྱི་བསླབ་བྱ་གནམ་རྩེང་ལྡེང་མ་བཞུགས་སོ།།
  subtitle: ''
  authors:
  - ' རྗེ་ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།'
  collection: Tsadra Geluk Series
  publisher: Tsadra Publishing
  id: TSD-GS-02
  cover: tmpq8d6inbk.jpg
  credit: tmp88ebl95y.jpg
